### ISSUE TITLE
Start-Button für Movie auf Titelzeile anbringen

### ISSUE THREAD

**Issue by ma4tu** [Shipmetrics/Tutorials#4]
![image](https://user-images.githubusercontent.com/19963598/30367702-3a13a59e-986f-11e7-89bc-94aa58e0bd69.png)

**Comment by K-Leon** [comment]
Nicht möglich, aber wir könnten den Suchbalken rausnehmen und ein kleines Suchfeld irgendwo einblenden - der Nutzer sollte sich denke ich da eh besser auf den Artikel fokussieren.
